### ISSUE TITLE
win10下面如何使用kcptun?

### ISSUE THREAD

**Issue by JeffreyChan** [mritd/dockerfile#100]
大神
  请问一下服务端创建好了docker镜像，在win10下面如何使用kcptun连接呀？

**Comment by mritd** [comment]
请查询对应客户端使用文档，这是只处理 docker 镜像问题。

**Comment by JeffreyChan** [comment]
主要是服务端的Kcptun似乎没有配置通讯密钥，加密方式这些？
能否给个demo?
还是谢谢了

**Comment by mritd** [comment]
说实话...我没有 windows 设备，而且也不使用 gui 的客户端，我两面全是 docker 😂

**Comment by JeffreyChan** [comment]
嗯，好的。大神的上推么，想fo大神。
