### ISSUE TITLE
运行kcptun client 报错

### ISSUE THREAD

**Issue by JeffreyChan** [mritd/dockerfile#101]
大神
我用kcptun client运行命令
kcpclient -r SSSERVER_IP:6500 -l :6500 -mode fast2
显示
An attempt was made to access a socket in a way forbidden by its access permissions.
上网搜索了一下，不知道如何解决。大神能否给点方向？

**Comment by mritd** [comment]
请给出具体运行环境等信息，方便我复现错误

**Comment by JeffreyChan** [comment]
win10 cmd
服务端是centos 7，就用的示例的命令运行的，只改了密码，其他什么都没有改。

**Comment by JeffreyChan** [comment]
win10下面的kcptun的客户端是client_windows_amd64.exe。
我觉得奇怪的是ss的端口是6443，kcptun的端口是6500，为何示例里面的UDP转发端口都是6500呢，其中一个应该是6443才对吧？
于是我把-l后面的改成6443了就看到连接成功了，也把ss客户端代理配置成127.0.0.1 6500了，但却无法翻墙了。

**Comment by JeffreyChan** [comment]
> 请给出具体运行环境等信息，方便我复现错误

具体环境信息是客户端的吗？因为服务端的ss一直可用，可以推测是成功的。
操作系统是：win10
kcptun的客户端是client_windows_amd64
暂时不知道还需要什么信息了
请大神详细说明一下。

**Comment by mritd** [comment]
windows 命令行问题请向官方仓库发起 issue，这个仓库只针对 docker 镜像问题进行处理
