### ISSUE TITLE
remove custom header 后又出现 failed to set TCP_FASTOPEN_CONNECT

### ISSUE THREAD

**Issue by maxduke** [mritd/dockerfile#108]
前天https://github.com/mritd/dockerfile/commit/23998d2bba406e20b28d564b9e1880018572d0a7 ， docker里SS又出现了 “failed to set TCP_FASTOPEN_CONNECT”

**Comment by mritd** [comment]
😂 这个是预期现象，因为 alpine 的 kernel 版本很高，宿主机 kernel 版本如果比较低就会出现这种问题；但是中核考虑 fastopen 似乎对性能影响不算太大；所以为了将来考虑我暂时删除了，如果有需要我尝试加一个自定义控制或者说明，因为我看官方也选择了跟随 alpine 主线版本 kernel，并没有做兼容动作。

**Comment by maxduke** [comment]
好点，了解了，多谢，新年快乐哈。

**Comment by mritd** [comment]
新年快乐 😀
