### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by wongweiwei** [mritd/dockerfile#11]
docker run -it -p 1080:1080 -p server_port:server_port/udp --name ss -e SS_CONFIG="-s 127.0.0.1 -p 1070 -l 1080 -k pwd1 -t 600 -m aes-256-cfb" -e KCP_CONFIG="-t server_ip:server_port -l :1070 -key pwd2 -crypt aes -mode fast2 -mtu 1350 -sndwnd 128 -rcvwnd 1024 -nocomp true" -e KCP_FLAG="true" -d mritd/shadowsocks

**Comment by mritd** [comment]
请提供错误日志，还有 对于 docker 内应用应当监听 0.0.0.0

**Comment by mritd** [comment]
暂时关闭了
