### ISSUE TITLE
希望提供一个更方便的privoxy，万分感谢

### ISSUE THREAD

**Issue by wjx0912** [mritd/dockerfile#111]
docker run -d --restart=always --name privoxy   -p 1080:8118  --forward-socks5t   "docker_host_ip:1079"   mritd/privoxy:v0.1

谢谢~~~

**Comment by mritd** [comment]
@Windfarer 没太明白，您希望 privoxy 支持命令行直接设置代理是么？

**Comment by mritd** [comment]
@wjx0912 

写完了，你试试 🤪🤪🤪

s2h => https://github.com/mritd/s2h
docker => https://github.com/mritd/autobuild/blob/main/earthfiles/s2h/Earthfile (关于为啥用这玩意后续我会写篇博客)

```sh
docker run --rm -it --network=host mritd/s2h -l 0.0.00:8888 -r 127.0.0.1:1080
```
