### ISSUE TITLE
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by cary-sas** [mritd/dockerfile#112]
the image "asuswrt-merlin-build"  cannot work on ubuntu ARM machine, is it possible to provide a version for ARM CPU?

**Comment by mritd** [comment]
I will try to build a docker image for the ARM platform tomorrow, But I am not sure if it can be built successfully.

**Comment by mritd** [comment]
@cary-sas I tried to build a docker image, but I am not proficient in building a Merlin system, do you have time to test this image： `mritd/asuswrt-merlin-build`

[![mritd/asuswrt-merlin-build](https://github.com/mritd/autobuild/actions/workflows/asuswrt-merlin-build.yaml/badge.svg)](https://github.com/mritd/autobuild/actions/workflows/asuswrt-merlin-build.yaml)

**Comment by cary-sas** [comment]
it looks still same 
![image](https://user-images.githubusercontent.com/61653855/139201832-fde7b053-001d-4108-9aa8-e1b518367248.png)

**Comment by mritd** [comment]
Sorry, after testing, some software installed according to the official documents of Merlin is not supported on the arm64 system.

So we cannot build the build image on linux/arm64, but we can cross-compile on the x86 platform

**Comment by cary-sas** [comment]
Thank you for helping me anyway!
