### ISSUE TITLE
樱花报错。Jun 29 09:22:13 UTC app name: mritd/shadowsocks process Exited with status 1

### ISSUE THREAD

**Issue by youxiaojie** [mritd/dockerfile#13]
cmd 为 /entrypoint.sh -s "-s 0.0.0.0 -p 8388 -m rc4-md5 -k youxiaojie --fast-open"  -k "-t 127.0.0.1:8388 -l :29900 -mode fast2" -x

**Comment by mritd** [comment]
樱花已经对代理工具做了封锁
