### ISSUE TITLE
shadowsocks新增加的ofbs测试。

### ISSUE THREAD

**Issue by eric21** [mritd/dockerfile#18]
docker run --restart=always -d -p 60001:60001 ss/ss -s "-s 0.0.0.0 -p 60001 -m chacha20-ietf-poly1305 -k is*******09 --fast-open --plugin obfs-server --plugin-opts 'obfs=tls'"

貌似命令格式不太对？虽然镜像成功启动了，但是TLS混淆没有开启。小火箭连接，开启TLS混淆连接不上。

**Comment by eric21** [comment]
解决了。去掉单引号就好了。233333333

**Comment by mritd** [comment]
@eric21 那我关了啊
