### ISSUE TITLE
brook的dockerfile，启动错误。

### ISSUE THREAD

**Issue by eric21** [mritd/dockerfile#19]
docker build -t brook/brook ./dockerfile/brook/

docker run --restart=always  -d -p 5789:5789 brook/brook "bkserver -l :5789 -p *** -t 10 -m chinaunicom_sales" 

用这个命令启动镜像之后，用docker ps -a 查看正在运行的容器，一直显示brook的容器运行错误。

\# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                                  PORTS                      NAMES
e2b197c2e73c        brook/brook         "./brook ' bkserve..."   6 seconds ago       Restarting (3) Less than a second ago                              jolly_wescoff

是不是命令格式不对？
非常感谢巨巨的辛苦劳动。

**Comment by mritd** [comment]
哈哈，我都藏得这么深还能被你找到... 等下我看看 啊

**Comment by mritd** [comment]
@eric21 

**Server**

``` sh
docker run -dt --name brook -p 8080:8080 mritd/brook brook bkserver -l :8080 -p test123,. -t 10 -m chinaunicom_sales
```

**Client**

``` sh
brook bkclient -s SERVER_IP:8080 -p test123,. -l :8080 -t 10 -m chinaunicom_sales
```

**Comment by eric21** [comment]
解决了，又是双引号的锅，2333333333333

**Comment by mritd** [comment]
Dockerfile 我更新了一下，hub 上已经有镜像了
