### ISSUE TITLE
mritd巨巨，求造个轮子。SSRR的dockerfile

### ISSUE THREAD

**Issue by eric21** [mritd/dockerfile#20]
https://github.com/shadowsocksrr/shadowsocksr/blob/akkariiin/master/Dockerfile
自从阿卡林接手了SSR之后，创建了akkariiin/master分支。新增加了auth_chain_c和auth_chain_d协议。
不知道他改动了哪里。旧的dockerfile已经不能用了。
求巨巨造个轮子，给我这样刚学会docker的小白，拜谢。

**Comment by Akkariiin** [comment]
https://github.com/shadowsocksrr/shadowsocksr/issues/8

**Comment by eric21** [comment]
FROM alpine

ENV SERVER_ADDR     0.0.0.0
ENV SERVER_PORT     51348
ENV PASSWORD        psw
ENV METHOD          none
ENV PROTOCOL        auth_chain_d
ENV PROTOCOLPARAM   32
ENV OBFS            tls1.2_ticket_auth
ENV TIMEOUT         300
ENV DNS_ADDR        8.8.8.8
ENV DNS_ADDR_2      8.8.4.4


RUN apk update \
    && apk add python \
    libsodium \
    unzip \
    wget \
  && rm -rf /var/cache/apk/*



RUN wget --no-check-certificate https://github.com/shadowsocksrr/shadowsocksr/archive/akkariiin/master.zip -O /tmp/master.zip \
    && unzip -d /tmp /tmp/master.zip \
    && mv /tmp/shadowsocksr-akkariiin-master ~/shadowsocksr \
    && rm -rf /tmp/*


WORKDIR ~/shadowsocksr/shadowsocks


EXPOSE 51348
CMD python ~/shadowsocksr/shadowsocks/server.py -p $SERVER_PORT -k $PASSWORD -m $METHOD -O $PROTOCOL -o $OBFS -G $PROTOCOLPARAM

用旧Dockerfile改了改，亲测可用。

**Comment by mritd** [comment]
我有时间尝试撸一个吧

**Comment by mritd** [comment]
😂 ss 分支太多了，我有点懵.......

**Comment by Akkariiin** [comment]
@mritd 现在就SS/SSR/SSRR三个分支
每个分支有Python/C#/Libev/Android(/IOS)几个实现
而已嘛.

只管Python的话 只需要三个版本就好(笑

**Comment by aiastia** [comment]
@eric21 这个的docker 下载下来的要怎么用

options :

command:

args:

这三个选项是什么
