### ISSUE TITLE
ss最新版的dockerfile是不是命令变了？

### ISSUE THREAD

**Issue by eric21** [mritd/dockerfile#22]
root@*:~# docker run --restart=always -d -p 6001:6001 ss/ss -s "-s 0.0.0.0 -p 6001 -m chacha20-ietf-poly1305 -k w*******xz --fast-open --plugin obfs-server --plugin-opts obfs=tls"
f0b43c43b1213c7e*********18dc8ecfaab17a86f6ee7ece27c7f
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"/entrypoint.sh\": permission denied".

**Comment by mritd** [comment]
参考 README 文档
