### ISSUE TITLE
请问shadowsocks镜像跑起来之后如何更改端口， VPS 重启后需要再重新跑一遍docker run 吗

### ISSUE THREAD

**Issue by kang000feng** [mritd/dockerfile#23]
谢谢大神的作品

**Comment by mritd** [comment]
跑起来之后就不可能再就改端口了，想要重启保持 docker 容器运行只需要 加 --restart=always 就可以了，不过一般推荐使用 docker compose 运行

**Comment by kang000feng** [comment]
谢谢大佬回复！那么改端口就只能docker rm 先删除重新搭建了吗？ 已经安装了compose ，不知道该如何编写模板文件运行shadosocks，大神能指点一下吗？

**Comment by mritd** [comment]
@kang000feng 可以参考官方文档  https://docs.docker.com/compose/gettingstarted/
