### ISSUE TITLE
有没有sample如何定义配置一个.yml运行mritd/shadowsocks

### ISSUE THREAD

**Issue by alexya** [mritd/dockerfile#33]
想通过 `docker stack up -c "${stack_file}" "${stack_name}"` 的方式 来运行这个docker mritd/shadowsocks
这里${stack_file}就是.yml的名字，然后${stack_name}则运行的container的名字。
例如：`docker stack up -c "./ssr.yml" "ss-server"`

请问怎么配置？谢谢！

**Comment by mritd** [comment]
关于 docker swarm 的配置我不太清楚，但是镜像配置与其他组件应该是一致的；请参考其他 swarm 集群样例配置修改即可。
