### ISSUE TITLE
[Proposal] udp2raw and UDPspeeder support

### ISSUE THREAD

**Issue by zzq889** [mritd/dockerfile#38]
参考来源：
[koolshare版梅林固件UDPspeeder和udp2raw串联的完整设置](https://github.com/wangyu-/UDPspeeder/wiki/koolshare%E7%89%88%E6%A2%85%E6%9E%97%E5%9B%BA%E4%BB%B6UDPspeeder%E5%92%8Cudp2raw%E4%B8%B2%E8%81%94%E7%9A%84%E5%AE%8C%E6%95%B4%E8%AE%BE%E7%BD%AE)

有没有可能增加 udp2raw 及 udpspeeder 的支持？

我不太确定直接放进 55 目前的容器里是否合适，尽管服务间都是串联，但是也是4个服务(55, kcptun, udp2raw, udpspeeder)了；也许单独跑容器然后用 docker service 的方式把服务 link 起来的方式会更优雅？如果是这样的 kcptun 是否也适合分拆出来？

**Comment by mritd** [comment]
@zzq889 暂时还真没有考虑集成这两个，一开始集成 kcp 也是出于使用方便；后来发现 udpspeeder 什么的 也不错，但是就如你所说；集成多了就太复杂了，而且 docker 本身的理念 就是 一个容器也只做一件事，单独容器 跑 docker-compose 实际上更好

**Comment by zzq889** [comment]
@mritd 我也是这么想的，我试试看都分拆出来吧，我可能先开个新的 repo 借鉴一些你现在的 Dockerfile
 如果你不反对的话。如果你想要以 pr 的形式我试验的差不多了提交上来。

**Comment by mritd** [comment]
@zzq889 可以

**Comment by mritd** [comment]
长时间无更新，关闭 issue。
