### ISSUE TITLE
Please add IPv6 support

### ISSUE THREAD

**Issue by YateSun** [mritd/dockerfile#43]
Please add IPv6 support, IPv6 is unavailable.

**Comment by mritd** [comment]
@YateSun shadowsocks ?

**Comment by YateSun** [comment]
应该是容器内没有IPv6网络环境吧，没有分配IPv6的地址。
一般的Docker容器，宿主服务器支持IPv6的情况下，容器内ping/curl google.com等，会优先走IPv6，也就是可以通过shadowsocks的代理，实现访问IPv6的资源。

**Comment by YateSun** [comment]
对，shadowsocks

**Comment by mritd** [comment]
ipv6 支持为 docker daemon 行为，与容器镜像无关

docker daemon 配置支持 ipv6 后 容器内才能有 ipv6 地址，具体请参考  [IPv6 with Docker](https://docs.docker.com/v17.09/engine/userguide/networking/default_network/ipv6/)

如果是 Digitalocean 用户，请参考 [Public IPv6 addresses for your Docker containers on Digitalocean](https://medium.com/@jonasotten/docker-on-digitalocean-with-a-public-ipv6-address-for-each-container-e908c73dbee6) **(已经亲自测试过 ok)**

**Comment by YateSun** [comment]
并不行，我是用alpine纯镜像是可以的。
Thank you.

**Comment by mritd** [comment]
@YateSun 请提供你的具体测试方法，以便复现

**Comment by YateSun** [comment]
我运行一个空的alpine镜像，IPv6网络一直是没有问题的
@mritd 我按照docker官网的文档按部执行下来，是能够获取到IPv6的IP了，但是在里面ping还是无法ping通

**Comment by YateSun** [comment]
我能尝试的方法，都尝试了，这个问题还是依然存在，所以只好放弃了。
现在用的Golang版本。
Thanks.
