### ISSUE TITLE
关于shadowsocks镜像请教几个问题

### ISSUE THREAD

**Issue by kowenzhang** [mritd/dockerfile#44]
非常感谢你提供这么好的梯子工具，有几个问题请教一下，忘有空解答：
1. 通过参数怎样设置用户名密码；
2. 开启kcptun对客户端有什么要求，官网的客户端是否可以使用kcptun加速；
3. 是否支持json配置文件，如何配置。

**Comment by mritd** [comment]
参数设置请查看文档 https://github.com/mritd/dockerfile/blob/master/shadowsocks/README.md
开启 kcptun 则支持 客户端采用 kcptun 链接，如果客户端没有采用 kcp，那么也可以链接原始端口
json 配置暂不支持，docker 镜像致力于微服务快速部署，如有需求可以 from 本 dockerfile 自行更改
