### ISSUE TITLE
shadowsocks的docker虽集成了obfs但未提供相关参数

### ISSUE THREAD

**Issue by danielsun1106** [mritd/dockerfile#45]
你好！shadowsocks的docker虽集成了obfs但未提供相关参数，麻烦抽空完善，多谢！
https://hub.docker.com/r/mritd/shadowsocks/

**Comment by mritd** [comment]
@danielsun1106 请问你指的 obfs 参数 值得是什么，是这个么 #24 ? 目前 bash 脚本对 obfs 解析有点小问题，但是不影响使用

**Comment by danielsun1106** [comment]
@mritd 你好，其实我真正想使用的是simple-obfs的`Standalone mode`，但一直未能找到与simple-obfs用法等价的参数，麻烦指点迷津，多谢！
```
obfs-server -s server_ip -p 8139 --obfs http -r 127.0.0.1:8388
ss-server -c config.json -s 127.0.0.1 -p 8388
```
如上例所示，访问8388端口时，用的是ss-server，而访问8139时，用的是obfs-server，这样比较灵活（考虑到部分客户端对obfs支持得不太好，所以也需要用到原始的ss-server）

**Comment by mritd** [comment]
抱歉，目前 `Standalone mode` 模式尚未支持，因为 [entrypoint.sh](https://github.com/mritd/dockerfile/blob/master/shadowsocks/entrypoint.sh) 脚本现在已经相当复杂了，我正在考虑有时限使用 go 写一个简单的包装程序，以支持这种特殊的命令请求

**Comment by danielsun1106** [comment]
理解，期待中 😉

**Comment by mritd** [comment]
@danielsun1106 最近试了一下 golang 包装，但是会造成镜像体积很大，光一个 golang 的包装程序就几 MB，现在考虑 单独做一个 obfs 镜像，或者提示使用 `--entrypoint` 覆盖哪个更好一些？

类似这样 `docker run --rm -it --entrypoint bash mritd/shadowsocks:3.1.3`

**Comment by danielsun1106** [comment]
殊途同归，对我而言，两种方式都能接受。
十分感谢为我提出的这个优化建议花费时间研究。

**Comment by mritd** [comment]
@danielsun1106 simple-obfs 单独的镜像已经开始构建，稍后将会发布在 [docker hub](https://hub.docker.com/r/mritd/simple-obfs/) 上，有时间可以测试一下是否 ok 😀

**Comment by danielsun1106** [comment]
@mritd 好的，麻烦也提供一下简明的操作文档，多谢 :-)

**Comment by mritd** [comment]
@danielsun1106 文档如下:

`simple-obfs` 的 `Standalone mode` 模式在整个 ss 配置组件中类似 `kcptun` 的位置，只不过 `kcptun` 为了加速，而 `simple-obfs` 为了流量混淆，在不增加 `kcptun` 的情况下整体请求流程如下:

``` sh
Client ==> ss client ==> simple-obfs-local ==> Firewall ==> simple-obfs-server ==> ss server ==> Real Server 
```

所以整个启动流程如下:

**Server 端**

``` sh
# 启动 ss
docker run -dt --name ss -p 1234:1234 mritd/shadowsocks -m "ss-server" -s "-s 0.0.0.0 -p 1234 -k testobfs -m chacha20"

# 启动 obfs server
docker run -dt --name obfs-server -p 443:443 mritd/simple-obfs obfs-server -v -s 0.0.0.0 -p 443 --obfs tls -r YOUR_SERVER_IP:1234
```
**Client 端**

``` sh
# 启动 obfs local
docker run -dt --name obfs-local -p 1234:1234 mritd/simple-obfs obfs-local -v -s YOUR_SERVER_IP -p 443 -b 0.0.0.0 -l 1234 --obfs tls --obfs-host www.bing.com

# 启动 ss
docker run -dt --name ss -p 1111:1111 mritd/shadowsocks -m "ss-local" -s "-s OBFS_LOCAL_HOST_IP -p 1234 -b 0.0.0.0 -l 1111 -k testobfs -m chacha20"
```
**注意: 虽然说 流量是先到达 `obfs-local` 然后转发到 `ss-local`，但是 `obfs-local` 配置中 `OBFS_LOCAL_HOST_IP` 不能为 `127.0.0.1`，因为 docker 网络是隔离的，应当设置为宿主机的局域网 IP**

**Comment by danielsun1106** [comment]
赞！我会尽快找时间试一下，谢啦！

**Comment by danielsun1106** [comment]
@mritd 刚试了一下，端口是打开了（可以telnet），但没有流量，我怀疑是网络问题，应该是我IP设置的有问题（虽然已按建议“设置为宿主机的局域网 IP”）
