### ISSUE TITLE
通过php7-fpm的Dockerfile创建镜像总是找不不到docker-php-source

### ISSUE THREAD

**Issue by waynesun01** [mritd/dockerfile#46]
已经将docker-php*的所有文件和Dockerfile放在同一目录下，创建时还是报错
/bin/sh: docker-php-source: not found
The command '/bin/sh -c apk upgrade --update     && apk ******  /var/cache/apk/*' returned a non-zero code: 127
不知是哪里错了，烦请指教，不甚感谢

**Comment by mritd** [comment]
sorry 这个 php 7 的 dockerfile 当时由于 php 官方没有 alpine 为基础景象时制作的，现在 hub 上官方已经维护了 基于 alpine 的，所以 你可以尝试直接采用官方的
