### ISSUE TITLE
希望可以client模式可以根据gfwlist.txt自动路由

### ISSUE THREAD

**Issue by HanYL-coder** [mritd/dockerfile#48]
希望可以client模式可以根据gfwlist.txt自动路由
文档中没有看到跟路由设置相关的信息.

**Comment by mritd** [comment]
@HanYL-coder 请问指的 那个镜像？😌

**Comment by HanYL-coder** [comment]
不好意思, 我好像把issue po错了项目.
我在用mritd/shadowsocks这个镜像, 很好用, 希望可以支持自动路由功能~

**Comment by mritd** [comment]
@HanYL-coder 你是说 shadowsocks client 模式增加 gfwlist.txt 配置么？client 模式 有这玩意么....
