### ISSUE TITLE
命令是已经用kcptun加速了吗？

### ISSUE THREAD

**Issue by Michael728** [mritd/dockerfile#53]
`docker run -dt --name ss -p 6443:6443 mritd/shadowsocks -s "-s 0.0.0.0 -p 6443 -m chacha20 -k test123 --fast-open"
`
请问这个命令是已经用kcptun加速了吗？还是说，还要按照其他教程，设置kcptun的加速？

**Comment by mritd** [comment]
并没有开启 
kcptun ，请参考 [README](https://github.com/mritd/dockerfile/blob/master/shadowsocks/README.md#%E5%91%BD%E4%BB%A4%E7%A4%BA%E4%BE%8B) 文档命令示例部分
