### ISSUE TITLE
Does this image support bbr?

### ISSUE THREAD

**Issue by jaggerwang** [mritd/dockerfile#55]
Can't get bbr status using the following command as said by this [article](https://github.com/iMeiji/shadowsocks_install/wiki/%E5%BC%80%E5%90%AFTCP-BBR%E6%8B%A5%E5%A1%9E%E6%8E%A7%E5%88%B6%E7%AE%97%E6%B3%95):

```
bash-4.4# sysctl net.ipv4.tcp_available_congestion_control
sysctl: error: 'net.ipv4.tcp_available_congestion_control' is an unknown key
bash-4.4# sysctl net.ipv4.tcp_congestion_control
sysctl: error: 'net.ipv4.tcp_congestion_control' is an unknown key
```

**Comment by mritd** [comment]
This image supports BBR.

BBR is provided by the Linux kernel. All docker containers share the Linux kernel; however, for security reasons, kernel parameters are not allowed to be modified in the docker container by default;

If you want to use the sysctl command in the docker container, you should start the container with the `--privileged` option (even if you don't use this option BBR still works).
