### ISSUE TITLE
群晖Docker跑 mritd/shadowsocks 崩溃

### ISSUE THREAD

**Issue by FormioCour** [mritd/dockerfile#59]
<img width="1077" alt="wx20181012-104314 2x" src="https://user-images.githubusercontent.com/36736095/46844953-caf7ce00-ce0b-11e8-8ae0-f730c386e6b5.png">

如图 不知啥原因,一直没启动成功，先生意外停止。
环境： 群晖上的Docker，映像拉取最新，并在高级设置-》执行命令-》命令 中写入`docker run -dt --name ssclient -p 1080:1080 mritd/shadowsocks -m "ss-local" -s "-s 服务器IP -p 服务器端口 -b 0.0.0.0 -l 1080 -m aes-256-cfb -k 服务器密码 --fast-open"`

**Comment by mritd** [comment]
从日志上看你的 `-s` 选项应该是没有生效，由于手里没有设备，我无法进行重现测试，我怀疑是群辉将终端参数进行了转义；你可以尝试使用声明环境变量的方式来使用；下面是每个选项对应应当声明的环境变量:

![image](https://user-images.githubusercontent.com/13043245/46917708-7bc4bf80-cffc-11e8-96d8-72c4aba10e3f.png)

**Comment by FormioCour** [comment]
命令写入 `docker run -dt --name ssclient -p 1080:1080 mritd/shadowsocks`  
在环境变量配置
`SS_MODULE` -> `ss-local`
`SS_CONFIG ` -> `"-s 服务器IP -p 服务器端口 -b 0.0.0.0 -l 1080 -m aes-256-cfb -k 服务器密码 --fast-open"`

一样启动不起来，直接崩溃。
群晖上的信息如下：
<img width="672" alt="wx20181014-224059 2x" src="https://user-images.githubusercontent.com/36736095/46918235-5470f100-d002-11e8-9e64-0d6d3672b684.png">
<img width="335" alt="wx20181014-224117 2x" src="https://user-images.githubusercontent.com/36736095/46918238-5d61c280-d002-11e8-9790-383d71183eb1.png">

**Comment by mritd** [comment]
@FormioCour 给我一下你得联系方式，我想具体看看

**Comment by mritd** [comment]
No response for a long time, close this issue.
