### ISSUE TITLE
跑docker run 出现以下错误 用latest 的image

### ISSUE THREAD

**Issue by JuneZhao** [mritd/dockerfile#61]
V2Ray v3.29 (die Commanderin) 20180705
A unified platform for anti-censorship.
Main: failed to read config file: /etc/v2ray/config.json > Main|Json: failed to execute v2ctl to convert config file. > Command|Platform|CtlCmd: v2ctl doesn't exist > stat /usr/bin/v2ctl: no such file or directory

**Comment by mritd** [comment]
请使用官方镜像吧，当初制作时官方镜像还不完善，现在已经很不错了；后续我将移除 v2ray 的 dockerfile

https://hub.docker.com/r/v2ray/official/

**Comment by JuneZhao** [comment]
hi 官方镜像我也是想用， 不过 怎么外挂config.json 文件呢，好像没有 环境变量可以写？ 类似这样？V2RAY_CONFIG_DIR

**Comment by mritd** [comment]
@JuneZhao 

```sh
docker run -dt --name v2ray -v `pwd`/config.json:/etc/v2ray/config.json v2ray/official
```

目前官方镜像唯一不好的一点是 tag 永远是 latest.....

**Comment by JuneZhao** [comment]
@mritd 多谢多谢，我在用azure container instance 跑这个，所以参数这边有些不一样不过调通了，多谢了
