### ISSUE TITLE
如何配置 ss-manage 管理多用户(多个端口/密码)

### ISSUE THREAD

**Issue by lilywang711** [mritd/dockerfile#63]
查了相关issue以及无法解决，我想在一个vps里配置多个端口对应多个密码

user_config.json里面配置如下
`
{
  "server":"0.0.0.0",
  "method": "aes-256-cfb",
  "local_address": "0.0.0.0",
  "local_port":6443,
  "port_password": {
    "8001": "test123",
    "8002": "test123",
    "8003": "test123"
  },
  "timeout":600,
  "fast_open": false
}
`
启动命令：

`docker run -dt --name ssserver \
     -p 6443:6443 -p 6500:6500/udp -v `pwd`/user_config.json:/config.json mritd/shadowsocks \
     -m "ss-manager" -s "-c /config.json" \`

然后在客户端配置8001端口，无法科学上网，请问是我哪里配置有问题吗？
thx

**Comment by mritd** [comment]
@lilywang711 https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose

**Comment by lilywang711** [comment]
@mritd 谢谢回复，但链接里的方法是容器端口 绑定 宿主机多端口呀，这样依旧不能绑定对应多个密码呀
> docker run -d -p 8000-9000:5000 xxxxx
