### ISSUE TITLE
filebeat 构建后启动报错

### ISSUE THREAD

**Issue by xuyangxy** [mritd/dockerfile#66]
filebeat 构建后启动报错如下：
  docker: Error response from daemon: Container command '/entrypoint.sh' could not be invoked.

构建的命令：  docker build -t hub.xxxx.com/xxxx/filebeat:6.5.2 .
启动： 
docker run \
 -v /usr/app/filebeat/filebeat.yml:/etc/filebeat.yml \
 -v /data/log:/data/log \
 --name filebeat -d \
 $IMAGE

问下大佬怎么解决呢 ？

**Comment by mritd** [comment]
能提供你的具体命令么？比如完整的命令复现截图，我刚刚测试完全没有问题

**Comment by xuyangxy** [comment]
下图是构建成功部分日志：
![image](https://user-images.githubusercontent.com/17880796/50204426-be5d9c00-039f-11e9-9b0d-aa02cf3a256e.png)

下图是生成镜像的日志：
![image](https://user-images.githubusercontent.com/17880796/50204460-ddf4c480-039f-11e9-82bf-51f43c48ab1f.png)

以下是启动信息：
![image](https://user-images.githubusercontent.com/17880796/50204817-0df09780-03a1-11e9-9da3-c7849fd32a40.png)

**Comment by fzitou** [comment]
build 之前执行
`chmod +x entrypoint.sh`

**Comment by mritd** [comment]
镜像一般都在 docker  hub 上采用了自动构建方式发布，所以你可以直接从 docker hub pull 镜像；在 dockerfile 中增加这种命令我认为是多余的
