### ISSUE TITLE
部署到heroku的问题

### ISSUE THREAD

**Issue by qu123xxx** [mritd/dockerfile#67]
你好，请问如果我把这个直接按照以下网址
https://devcenter.heroku.com/articles/container-registry-and-runtime
的内容部署到heroku需要如何设置或者添加一些什么文件呢？

**Comment by mritd** [comment]
如果你指的是 ss 的 docker image: 

> 公有容器平台由于其网络不确定性以及各家厂商的复杂实现，已经停止支持；停止支持并不意味着容器不支持运行在公有容器平台，而是说你需要自己去寻找解决方案；比如网络连通性测试、参数设置测试等；

如果不是 ss 的 docker image: 

> 这个仓库目前包含大部分个人日常使用的 docker 镜像的 image，如果想部署到公有云平台，请自行复制相关目录、修改 Dockerfile 以满足公有云平台要求

**Comment by qu123xxx** [comment]
谢谢你，我刚刚试了下，上传到某一步了就传不上去了，显示不支持，我试了几个别的SS的docker image传上去了但是也不知道怎么调试。
