### ISSUE TITLE
UDP转发失败

### ISSUE THREAD

**Issue by Yuan-ZW** [mritd/dockerfile#69]
我用仅用这个命令启动的服务：
`docker run -dt --name ssserver -p 6443:6443 -p 6500:6500/udp mritd/shadowsocks -m "ss-server" -s "-s 0.0.0.0 -p 6443 -m chacha20 -k mypasswd --fast-open" -x -e "kcpserver" -k "-t 127.0.0.1:6443 -l :6500 -mode fast2"`
TCP连接没问题， 但用SSTap测试UDP转发不通过。请问我有漏了什么步骤吗，还是说我哪里用错了？
![sstap](https://user-images.githubusercontent.com/31435244/51440617-df4d4000-1d03-11e9-8318-34422b762ac5.png)

麻烦大佬给解解答，谢了！

**Comment by pengcu** [comment]
开启 6443 的udp 
`-p 6443: 6443/udp`

**Comment by zozovo** [comment]
尝试添加 `-u` 参数试试（但好像是默认 `-u`）：
``` bash
docker run -dt \
--name ssserver \
-p 6443:6443 \
-p 6500:6500/udp \
mritd/shadowsocks \
-m "ss-server" \
-s "-s 0.0.0.0 -p 6443 -m chacha20 -k mypasswd --fast-open -u" \
-x \
-e "kcpserver" \
-k "-t 127.0.0.1:6443 -l :6500 -mode fast2"
```
另外如果用不到 kcptun 的话，建议在同端口上开启 udp ：
```bash
docker run -d
-p 6443:6443 \
-p 6443:6443/udp \
mritd/shadowsocks \
-s "-s 0.0.0.0 -p 6443 -m chacha20 -k mypasswd -u --fast-open "
 ```

**Comment by Yuan-ZW** [comment]
@zozovo 
> 尝试添加 `-u` 参数试试（但好像是默认 `-u`）：

感谢！

果然加上`-p 6443:6443/udp`，
再加上`-u`就行了。

我之前只尝试过加了udp端口映射没加`-u`，
因为看到说默认`-u`，就一直没去尝试，
现在看来两个都要加

我最终是这么用的:
```
docker run -dt \
--name ssserver \
-p 6443:6443 \
-p 6443:6443/udp \
-p 6500:6500/udp \
mritd/shadowsocks \
-m "ss-server" \
-s "-s 0.0.0.0 -p 6443 -m chacha20 -k mypasswd -u --fast-open" \
-x \
-e "kcpserver" \
-k "-t 127.0.0.1:6443 -l :6500 -mode fast2"
```

**Comment by mritd** [comment]
如果没问题，我将 issue 关闭了
