### ISSUE TITLE
docker run 改为kubectl run

### ISSUE THREAD

**Issue by MySource14** [mritd/dockerfile#70]
最近开始试用您的image，真的很简便又有效；现在想把SS部署在IBM的bluemix上，现在bluemix 只能用kubectl做部署，因为您的image中需要暴露两个不同的端口，我刚刚接触bluemix，实在不知道怎么样在Bluemix上部署。可否帮忙解答一下？多谢啦！

**Comment by mritd** [comment]
对于 kubernetes 集群，你需要创建 deployment 配置文件，并增加适当的端口映射即可

kubernetes  deployment 文档请参考  https://kubernetes.io/zh/docs/concepts/workloads/controllers/deployment/

由于我没有使用过 bluemix，所以对其服务暴露方式并不了解，但是 kubernetes 基础设施应当允许创建 Ingress 从而暴露 TCP/UDP 服务端口，这些操作可能需要创建  [service](https://kubernetes.io/zh/docs/concepts/services-networking/service/) 和 [ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/)

**Comment by MySource14** [comment]
多谢回复，我先研究一下。

**Comment by MySource14** [comment]
昨天折腾了几个小时，安装成功，加速后速度提升15倍左右。
Bluemix的容器多端口暴露只能通过deployment的YAML配置文件完成，然后通过expose命令建立service暴露的external IP上。
另外，在Bluemix上的启动只能用环境变量的方式启动您的镜像，因为kubectl run似乎不支持包括双引号的参数（我试验没有成功）。
