### ISSUE TITLE
能提供一个安卓kcp示例吗

### ISSUE THREAD

**Issue by logicinu** [mritd/dockerfile#71]
服务端
```
docker run -dt --name ssserver -p 6443:6443 -p 6500:6500/udp mritd/shadowsocks -m "ss-server" -s "-s 0.0.0.0 -p 6443 -m chacha20 -k test123 --fast-open" -x -e "kcpserver" -k "-t 127.0.0.1:6443 -l :6500 -mode fast2"
```
客户端
```
docker run -dt --name ssclient -p 1080:1080 mritd/shadowsocks -m "ss-local" -s "-s 127.0.0.1 -p 6500 -b 0.0.0.0 -l 1080 -m chacha20 -k test123 --fast-open" -x -e "kcpclient" -k "-r SSSERVER_IP:6500 -

l :6500 -mode fast2"
```
在电脑上是可以连接上的，但是到了安卓上就不知道怎么做了。

![screenshot_20190208-231351_shadowsocks](https://user-images.githubusercontent.com/43819414/52487222-1c686c00-2bf8-11e9-889e-fe318d24f872.png)
![screenshot_20190208-231357_shadowsocks](https://user-images.githubusercontent.com/43819414/52487252-30ac6900-2bf8-11e9-839c-3e8d14fe4a1d.png)
配置
```
key=;crypt=none;mode=fast2;mtu=1350;sndwnd=128;rcvwnd=512;datashard=10;parityshard=3;dscp=0;nocomp;quiet
```
请问配置哪里有问题了，求助。

**Comment by mritd** [comment]
... 这个，有点抱歉...我没有安卓机 😂

**Comment by logicinu** [comment]
安卓模拟器？

**Comment by zozovo** [comment]
已经排除掉运营商对 UDP 进行 QoS 的可能？

**Comment by Yuan-ZW** [comment]
`key=;`这里错了，应该是`key=it's a secrect;`

事实上你可以完全不写，默认就是`key=it's a secrect`，
写了`key=`反而表示key是空字符串。

同理，按照你server的配置，在client中你可以把配置里面除了`mode=fast2`以外的全删掉

就像这样
![_20190214102057](https://user-images.githubusercontent.com/31435244/52758215-6d39f380-3042-11e9-8d56-7b83faa7e714.jpg)

**Comment by Yuan-ZW** [comment]
> ... 这个，有点抱歉...我没有安卓机 😂

顺便帮朋友问一下，苹果手机上有没有支持kcp的ss客户端？ @mritd

**Comment by mritd** [comment]
@Yuan-ZW 暂时我没看到有什么支持的...

**Comment by mritd** [comment]
@logicinu 是否还有相关问题？如果没问题了，我将 issue 关闭
