### ISSUE TITLE
Unrecognized option: (null)

### ISSUE THREAD

**Issue by zzk1314** [mritd/dockerfile#72]
描述：CentOs 7.2 新机器安装Docker后使用如下命令启动，但是报错Unrecognized option: (null) 
完全不知道报错原因。。。。 同样的命令在其他机器上可以运行

sudo docker run -dt --name ssserver -p 6443:6443 -p 6500:6500/udp mritd/shadowsocks -m "ss-server" -s "-s 0.0.0.0 -p 6443 -m aes-256-cfb -k test --fast-open" -x -e "kcpserver" -k "-t 127.0.0.1:6443 -l :6500 -mode fast2"

`
Kcptun not started......
Starting shadowsocks......
 2019-02-13 17:19:42 ERROR: Unrecognized option: (null)

shadowsocks-libev 3.2.3

  maintained by Max Lv <max.c.lv@gmail.com> and Linus Yang <laokongzi@gmail.com>

  usage:

    ss-server
`

**Comment by mritd** [comment]
请提供下  docker 版本、内核版本

从日志上看是选项不对，如果如果你的命令确认完全没问题的话，那么有可能是 docker 版本问题

建议使用 Ubuntu 16/18 运行 docker，centos7 在容器化方面并不那么 ok

**Comment by mritd** [comment]
Not replying too long, close this issue.
