### ISSUE TITLE
从3.2.1升级到3.2.4报错：failed to set TCP_FASTOPEN_CONNECT

### ISSUE THREAD

**Issue by ichrislu** [mritd/dockerfile#73]
容器运行，docker-compose
操作系统版本：CentOS Linux release 7.5.1804 (Core)
Docker版本：Server Version: 18.09.0
启动参数：command: -m "ss-server" -s "-s 0.0.0.0 -p 8388 -m aes-256-cfb -k ****** --fast-open" -x -e "kcpserver" -k "-t 127.0.0.1:8388 -l :8500 -mode fast2"

同样的启动参数，之前3.2.1版本运行正常，升级3.2.4版本后，容器启动一会儿后就退出了，报错信息如下：
Starting kcptun......
Starting shadowsocks......
 2019-03-04 10:53:55 INFO: using tcp fast open
 2019-03-04 10:53:55 INFO: initializing ciphers... aes-256-cfb
 2019-03-04 10:53:55 INFO: tcp server listening at 0.0.0.0:8388
 2019-03-04 10:53:55 INFO: running from root user
2019/03/04 10:53:55 version: 20190109
2019/03/04 10:53:55 initiating key derivation
2019/03/04 10:53:55 listening on: [::]:8500
2019/03/04 10:53:55 target: 127.0.0.1:8388
2019/03/04 10:53:55 encryption: aes
2019/03/04 10:53:55 nodelay parameters: 1 20 2 1
2019/03/04 10:53:55 sndwnd: 1024 rcvwnd: 1024
2019/03/04 10:53:55 compression: true
2019/03/04 10:53:55 mtu: 1350
2019/03/04 10:53:55 datashard: 10 parityshard: 3
2019/03/04 10:53:55 acknodelay: false
2019/03/04 10:53:55 dscp: 0
2019/03/04 10:53:55 sockbuf: 4194304
2019/03/04 10:53:55 keepalive: 10
2019/03/04 10:53:55 snmplog:
2019/03/04 10:53:55 snmpperiod: 60
2019/03/04 10:53:55 pprof: false
2019/03/04 10:53:55 quiet: false
2019/03/04 10:54:04 remote address: 14.155.223.114:57855
2019/03/04 10:54:21 remote address: 14.155.223.114:62448
2019/03/04 10:54:21 stream opened
 2019-03-04 10:54:21 ERROR: failed to set TCP_FASTOPEN_CONNECT

**Comment by ichrislu** [comment]
删除参数“--fast-open”就好了，估计旧版本忽略了这个参数，或者程序做了兼容处理
还没尝试Linux启用TFO行不行

**Comment by mritd** [comment]
有时间我处理下这个问题

refs shadowsocks/shadowsocks-libev#2133

**Comment by ichrislu** [comment]
已测试，Linux启用TFO不行

**Comment by mritd** [comment]
@ichrislu 重新 build 了一下，你试试 `docker rmi mritd/shadowsocks:3.2.4` 然后重新运行

**Comment by ichrislu** [comment]
仍然不行，只要有连接建立，就报以下错误，不管有没有启用TFO
ERROR: failed to set TCP_FASTOPEN_CONNECT

凑合也能用 :)

**Comment by mritd** [comment]
@ichrislu 你的内核版本号是多少？

**Comment by longwdl** [comment]
我也是一样的问题

内核版本`4.4.0-116-generic #140-Ubuntu`

**Comment by ichrislu** [comment]
> @ichrislu 你的内核版本号是多少？

3.10.0-862.3.2.el7

**Comment by mritd** [comment]
@ichrislu @longwdl 

我在 Ubuntu 18(4.15.0-43-generic) 上测试并没有出现 issue 描述的错误，但是会出现其他错误

![image](https://user-images.githubusercontent.com/13043245/53928726-1d40d080-40c6-11e9-9370-e908f5a45f1c.png)

同时我测试了官方镜像一样会出现这个问题 

![image](https://user-images.githubusercontent.com/13043245/53928777-524d2300-40c6-11e9-9280-4dec64287cbf.png)

**Comment by zongwei007** [comment]
我的系统版本是 `Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-1075-aws x86_64)`，同样遇到 `failed to set TCP_FASTOPEN_CONNECT` 问题。

**Comment by ichrislu** [comment]
> @ichrislu @longwdl
> 
> 我在 Ubuntu 18(4.15.0-43-generic) 上测试并没有出现 issue 描述的错误，但是会出现其他错误
> 
> ![image](https://user-images.githubusercontent.com/13043245/53928726-1d40d080-40c6-11e9-9370-e908f5a45f1c.png)
> 
> 同时我测试了官方镜像一样会出现这个问题
> 
> ![image](https://user-images.githubusercontent.com/13043245/53928777-524d2300-40c6-11e9-9280-4dec64287cbf.png)

那可能是官方版本的bug，先凑合用吧

**Comment by xsir99** [comment]
同样的问题，升级内核4.10.2-041002-generic后出现, 用的没有问题...

**Comment by mritd** [comment]
我怀疑可能是 alpine 内核 header 版本过高导致的，我有时间仔细看一下，可以暂时关闭一下 TFO

**Comment by mritd** [comment]
@xsir99 @ichrislu @longwdl @zongwei007 请使用 `3.2.4-20190321` 的 tag 重新测试一下，根据测试 alpine 3.9 版本 kernel-headers 升级到了 4.18，内核部分 TFO 可能出现了不兼容变化，现在手动降级到了 4.4 kernel-headers 进行编译

**Comment by ichrislu** [comment]
> @xsir99 @ichrislu @longwdl @zongwei007 请使用 `3.2.4-20190321` 的 tag 重新测试一下，根据测试 alpine 3.9 版本 kernel-headers 升级到了 4.18，内核部分 TFO 可能出现了不兼容变化，现在手动降级到了 4.4 kernel-headers 进行编译

可以用，日志有如下错误，应该不影响
ERROR: fast open is not supported on this platform

**Comment by mritd** [comment]
问题根本原因是 TFO 开启需要编译时依赖 kernel-headers，而内核头文件版本在 alpine(或者其他系统)中会不断更新；

**编译后的 target 文件只能保证在在其依赖的 kernel-headers 相同版本的 kernel 上没有问题**；由于 docker 运行时内核版本取决于宿主机内核版本，所以同样地镜像在不同系统下内核 TFO 上会有不同的表现行为

**这个问题没有根本的解决办法，我目前能做的只能是尽量降低，或者说是选择一个适中的版本，来保证大部分用户没有问题**；最后推荐使用 Ubuntu 系统运行 docker，如果可能可以采用 Ubuntu 18 跑 docker。

**Comment by zongwei007** [comment]
已变更 tag 为 `3.2.4-20190321` 并开启 `--fast-open`，使用正常。
