### ISSUE TITLE
hyper-v的ubuntu 18运行Client端，海外服务器运行Server端，似乎没作用

### ISSUE THREAD

**Issue by liaokaime** [mritd/dockerfile#76]
我按照docker hub上的示例。
Server（Ubuntu 16）运行：
```docker run -dt --name ssserver -p 6455:6455 -p 6458:6458/udp mritd/shadowsocks -m "ss-server" -s "-s 0.0.0.0 -p 6455 -m chacha20 -k test123 --fast-open" -x -e "kcpserver" -k "-t 127.0.0.1:6455 -l :6458 -mode fast2"```，
虚拟机（Ubuntu18）：
```docker run -dt --name ssclient -p 1080:1080 mritd/shadowsocks -m "ss-local" -s "-s 127.0.0.1 -p 6458 -b 0.0.0.0 -l 1080 -m chacha20 -k test123 --fast-open" -x -e "kcpclient" -k "-r 45.77.198.241:6458 -l :6458 -mode fast2"```
本机运行Shadowsocks 4.1.4，服务器填虚拟机IP，加密方式填```chacha20```，端口填```1080```，密码填```test123```
尝试上google，但上不去，请问我哪一步出问题了吗？

**Comment by mritd** [comment]
请提供日志

**Comment by liaokaime** [comment]
神速回复啊。请问日志在在哪里呢

**Comment by mritd** [comment]
`docker logs CONTAINER_ID`

**Comment by liaokaime** [comment]
```
root@vultr:~# docker logs 21cce370f24b
Starting kcptun......
Starting shadowsocks......
 2019-03-12 10:35:25 INFO: using tcp fast open
 2019-03-12 10:35:25 INFO: initializing ciphers... chacha20
 2019-03-12 10:35:25 INFO: tcp server listening at 0.0.0.0:6443
 2019-03-12 10:35:25 INFO: running from root user
2019/03/12 10:35:25 version: 20190109
2019/03/12 10:35:25 initiating key derivation
2019/03/12 10:35:25 listening on: [::]:6500
2019/03/12 10:35:25 target: 127.0.0.1:6443
2019/03/12 10:35:25 encryption: aes
2019/03/12 10:35:25 nodelay parameters: 1 20 2 1
2019/03/12 10:35:25 sndwnd: 1024 rcvwnd: 1024
2019/03/12 10:35:25 compression: true
2019/03/12 10:35:25 mtu: 1350
2019/03/12 10:35:25 datashard: 10 parityshard: 3
2019/03/12 10:35:25 acknodelay: false
2019/03/12 10:35:25 dscp: 0
2019/03/12 10:35:25 sockbuf: 4194304
2019/03/12 10:35:25 keepalive: 10
2019/03/12 10:35:25 snmplog:
2019/03/12 10:35:25 snmpperiod: 60
2019/03/12 10:35:25 pprof: false
2019/03/12 10:35:25 quiet: false
2019/03/12 10:35:48 remote address: 171.34.76.92:31649
root@vultr:~#

```

**Comment by liaokaime** [comment]
使用SwitchyOmega后正常使用，在CS端命令都去除```--fast-open```参数的情况下

**Comment by mritd** [comment]
你应该是使用了 本地 的 ss 客户端链接了 本地 linux 上的 ssclient 端口吧？

**Comment by liaokaime** [comment]
是的，刚开始是这样做的
