### ISSUE TITLE
请求shadowsocks支持http代理

### ISSUE THREAD

**Issue by Nillouise** [mritd/dockerfile#79]
rt

**Comment by mritd** [comment]
目前 shadowsocks 镜像除了会继续继承 obfs 相关组件外，不会再继续集成需要守护型运行的其他程序

目前镜像内部包含 kcptun、shadwsocks 已经违反了 docker 理念(目前采用 runit 缓解)，如果继续集成类似 privoxy 的工具，会导致镜像越来越大，配置文件、CLI 选项变得庞大不可维护

如果你希望 shadowsocks 能够提供 http 端口暴露(例如用于终端代理使用)，那么你可以使用 [privoxy](https://github.com/mritd/dockerfile/tree/master/privoxy) 启动一个新容器进行转换，这样更加方便并且可维护性更高
