### ISSUE TITLE
Where can I see the shadowsocks log file?

### ISSUE THREAD

**Issue by jacauc** [mritd/dockerfile#82]
Where can I see the shadowsocks log file?

**Comment by mritd** [comment]
shadowsocks log output to stdout by default.

**Comment by jacauc** [comment]
I'd like to keep a log in the docker image, but I am unable to find this
file, or an option to enable it?

**Comment by mritd** [comment]
Log output to the file is currently not supported and is not ready to be added in the future for two reasons:

- The log will become larger and larger after being written to the file. For this reason, we may also consider the more complicated cases of log segmentation, cleanup, etc.
- Writing to a file may burden the log collection system for large-scale deployments (such as k8s)

**Comment by jacauc** [comment]
Understand that completely. Can you maybe give me advice on how I can hack
it together for my docker image?  I'm willing to accept those risks as it
is a very small deployment on my Nas, only for personal use, so I can
manage the logs manually if they grow too large.

I can write a script for log rotation and deleting logs older than x days

**Comment by mritd** [comment]
I will write a dockerfile sample for you later. 😜

**Comment by jacauc** [comment]
Thanks!!

I also have shell access to the docker, so if it's just a few commands, I'd
be happy to do it myself

**Comment by mritd** [comment]
@jacauc 

I have modified the completion and support the log output to the file's shadowsocks located at the feat/ss-log2file branch

**Comment by mritd** [comment]
This is the difference file 

``` diff
diff --git a/shadowsocks/entrypoint.sh b/shadowsocks/entrypoint.sh
index 37a8d7c..3d9fd6d 100755
--- a/shadowsocks/entrypoint.sh
+++ b/shadowsocks/entrypoint.sh
@@ -5,8 +5,9 @@ SS_MODULE=${SS_MODULE:-"ss-server"}
 KCP_CONFIG=${KCP_CONFIG:-""}
 KCP_MODULE=${KCP_MODULE:-"kcpserver"}
 KCP_FLAG=${KCP_FLAG:-"false"}
+LOG_FILE=${LOG_FILE:-"/dev/stdout"}
 
-while getopts "s:m:k:e:x" OPT; do
+while getopts "s:m:k:e:o:x" OPT; do
     case $OPT in
         s)
             SS_CONFIG=$OPTARG;;
@@ -16,6 +17,8 @@ while getopts "s:m:k:e:x" OPT; do
             KCP_CONFIG=$OPTARG;;
         e)
             KCP_MODULE=$OPTARG;;
+        o)
+            LOG_FILE=$OPTARG;;
         x)
             KCP_FLAG="true";;
     esac
@@ -25,6 +28,7 @@ export SS_CONFIG=${SS_CONFIG}
 export SS_MODULE=${SS_MODULE}
 export KCP_CONFIG=${KCP_CONFIG}
 export KCP_MODULE=${KCP_MODULE}
+export LOG_FILE=${LOG_FILE}
 export KCP_FLAG=${KCP_FLAG}
 
 exec runsvdir -P /etc/service
diff --git a/shadowsocks/runit/kcptun/run b/shadowsocks/runit/kcptun/run
index 36f8c5d..8b5a60f 100755
--- a/shadowsocks/runit/kcptun/run
+++ b/shadowsocks/runit/kcptun/run
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+exec >> ${LOG_FILE}
 exec 2>&1
 
 if [ "${KCP_FLAG}" == "true" ]; then
diff --git a/shadowsocks/runit/shadowsocks/run b/shadowsocks/runit/shadowsocks/run
index bd9f12c..e5773af 100755
--- a/shadowsocks/runit/shadowsocks/run
+++ b/shadowsocks/runit/shadowsocks/run
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+exec >> ${LOG_FILE}
 exec 2>&1
 
 if [ -z "${SS_MODULE}" ]; then
```

**Comment by jacauc** [comment]
Fantastic! I'll try it soon! Thanks

**Comment by mritd** [comment]
Is it working properly? If there are no problems, I will close the issue.

**Comment by jacauc** [comment]
Hi, I'm unfortunately out of country for work at present, so I couldn't
test it yet. I'm sure it's all okay though. You can close the issue and
once I get to test it, I'll let you know.

Thanks!

**Comment by mritd** [comment]
I will keep this issue open until you finish testing. 😊

**Comment by jacauc** [comment]
This works well thanks. Not giving me all the info I was looking for, but that seems to be a limitation of ss-server itself. Appreciate it!

**Comment by mritd** [comment]
Ok, I will close this issue, you can reopen it at any time.
