### ISSUE TITLE
mritd/shadowsocks bind port Permission denied

### ISSUE THREAD

**Issue by op69qs** [mritd/dockerfile#83]
使用最新Dockerfile 绑定任何端口 都提示 ERROR: bind: Permission denied

` mritd/shadowsocks -m "ss-server" -s "-s 0.0.0.0 -p 443 -k sefsdf -m chacha20-ietf-poly1305 -t 1200 -u -d 1.1.1.1,1.0.0.1 -a root"`

**Comment by mritd** [comment]
是否有必要的场景需要强制绑定到低位端口？
因为 docker 运行时无论你里面绑定什么端口，最终由外部映射端口决定

``` sh
# 最终暴露端口为 1234
docker run --rm -it -p 1234:1111 some_image
```

**Comment by op69qs** [comment]
emmmm 有道理

**Comment by mritd** [comment]
好的，那么我关闭这个 issue，如果有其他问题请随时重新打开
