### ISSUE TITLE
可否增加一个 admin 管理端

### ISSUE THREAD

**Issue by zoulux** [mritd/dockerfile#87]
看到网上有很多 ss 的 admin 管理端，可以增加账户，可以增加设置用户流量限额

**Comment by mritd** [comment]
shadowsocks-manager 官方有镜像

**Comment by zoulux** [comment]
@mritd 
可否提供镜像地址

**Comment by mritd** [comment]
@zoulux https://github.com/shadowsocks/shadowsocks-manager#from-docker
