### ISSUE TITLE
shadowsocks2能否支持obfs

### ISSUE THREAD

**Issue by crabhit** [mritd/dockerfile#90]
由于未知的原因go版本的SS在我的服务器上更加稳定一些 能否给shadowsocks2添加obfs支持?

**Comment by mritd** [comment]
@crabhit go 版本的 shadowsocks2 原生不支持 plugin，所以内置 obfs 也毫无意义，使用 go 的shadowsocks2 推荐使用官方仓库的 Dockerfile，本仓库的 Dockerfile 仅供个人 DIY 使用

**Comment by mritd** [comment]
长时间无反馈，issue 关闭
