### ISSUE TITLE
mritd/shadowsocks 的问题

### ISSUE THREAD

**Issue by idogstar** [mritd/dockerfile#93]
我在qnap nas上通过docker 安装配置完成mritd/shadowsocks ss和kcptun客户端。在电脑上通过ss客户链接上docker的ip的也能加速和翻墙。

我的问题是通过dockerip:1080 作为代理服务器地址配置到电脑就上，就显示链接被拒绝。是不是dcoker的ss 不支持通过1080代理上网。

**Comment by mritd** [comment]
1080 端口 是 本地监听 socks5 端口，你贴一下完整的复现流程 否则我没办法测试

**Comment by idogstar** [comment]
我是在家用QNAP nas（ip 10.0.0.10）安装的，给dockER分配的ip 为10.0.0.25

执行的命令如下 /entrypoint.sh -m "ss-local" -s "-s 127.0.0.1  -p 3400 -b 0.0.0.0 -l 1080 -m rc4-md5 -k ***KEY***" -x -e "kcpclient" -k "-r 国外远程vpsIP:端口 -l :3400 -mode fast2 -crypt aes-192 -key ***KEY***"

在电脑（ip：10.0.0.14）上的ss客户端上设置好相应的服务器ip为10.0.0.25及端口，密码，确实加速上了，说明kcp加速正常。

但是我想让家里的其他设备可以通过设置http代理的方式来科学上网，所以设置了代理为10.0.0.25:1080，然后就打不开任何网页，提示代理拒绝访问。

不知道是不是这个docker里的ss并不支持http代理

**Comment by mritd** [comment]
这是正常的，ss local 1080是 socks5 协议端口，不提供 http 服务，你有两种选择，一种让客户端直接使用 socks5 去连接，另一种你再启动一个 privoxy 容器将 socks5 转换成 http 代理

**Comment by idogstar** [comment]
感谢答复。

mritd <notifications@github.com> 于2019年10月16日周三 下午2:19写道：
