### ISSUE TITLE
作为客户端的情况下如何设置PAC自动或者全局？

### ISSUE THREAD

**Issue by nathan-guo** [mritd/dockerfile#98]
作为客户端的情况下如何设置PAC自动或者全局？

谢谢。

**Comment by mritd** [comment]
客户端只提供标准的 socks5 代理，不会提供其他任何功能，需要 pac 或者其他功能的请自行采用其他规则代理工具处理，client 模式下只是单纯的运行 ss-local，所以 ss-local 不提供的功能本镜像也无法提供
